---
- name: Add repository
  stat:
    path: /etc/apt/sources.list.d/nodesource.list
  register: source

- name: Setup Node.js {{ nodejs_version }}.x
  shell: "curl -sL https://deb.nodesource.com/setup_{{ nodejs_version }}.x | bash -"
  args:
    warn: no
  when: not source.stat.exists
