---
- name: Add repository
  stat:
    path: /etc/apt/sources.list.d/nodesource.list
  register: source

- name: Setup Node.js 14.x
  shell: curl -sL https://deb.nodesource.com/setup_14.x | bash -
  args:
    warn: no
  when: not source.stat.exists
