---
- name: Add repository
  stat:
    path: /etc/yum.repos.d/nodesource-el7.repo
  register: source

- name: Setup Node.js 14.x
  shell: curl -sL https://rpm.nodesource.com/setup_14.x | bash -
  args:
    warn: no
  when: not source.stat.exists
