---
- name: Put test script
  template:
    src: files/test_env.py
    dest: /tmp/test_env.py
  tags:
    - infratest

- name: Run test script
  command: py.test /tmp/test_env.py
  changed_when: False
  tags:
    - infratest
