---
debian:
  remove_packages:
    - docker
    - docker.io
    - containerd
    - runc

  dep_packages:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

  add_packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

redhat:
  remove_packages:
    - docker
    - docker-client
    - docker-client-latest
    - docker-common
    - docker-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-engine

  dep_packages:
    - yum-utils

  add_packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io
