---
add_packages:
  - stunnel4

certbot_auto_renew: true
certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
certbot_auto_renew_options: --quiet --no-self-upgrade
certbot_auto_renew_hour:   "4"
certbot_auto_renew_minute: "10"

certbot_create_command: >-
  certbot certonly --standalone --noninteractive --agree-tos
    --email {{ cert_item.email }}
    -d {{ cert_item.domains | join(',') }}
