---
symbol_platform_config_preset: testnet
symbol_platform_config_assembly: dual
symbol_platform_config_pswd: sekoya

symbol_platform_user_name: symbol
symbol_platform_user_pswd: sekoya

symbol_platform_renew_voting_key_day: "1"
symbol_platform_renew_voting_key_hour: "5"
symbol_platform_renew_voting_key_minute: "30"
