---
- name: Install monit
  package:
    name: "{{ add_packages }}"
    state: present
    update_cache: yes
  tags:
    - monit

- name: Ensure monit service is enabled
  systemd:
    name: monit
    state: started
    enabled: yes
    daemon_reload: yes
  tags:
    - monit

- name: Replace monitrc
  template:
    src: templates/monitrc.j2
    dest: /etc/monit/monitrc
  notify:
    - restart monit
  tags:
    - monit
