---
- name: Install fail2ban
  package:
    name: "{{ add_packages }}"
    state: present
    update_cache: yes
  tags:
    - fail2ban

- name: Ensure fail2ban service is enabled
  systemd:
    name: fail2ban
    state: started
    enabled: yes
    daemon_reload: yes
  tags:
    - fail2ban

- name: Gather package facts
  package_facts:
    manager: auto
  tags:
    - fail2ban

- name: Create link for fail2ban
  file:
    src:  /etc/monit/monitrc.d/fail2ban
    dest: /etc/monit/conf-enabled/fail2ban
    state: link
  when: "'monit' in ansible_facts.packages"
  notify:
    - restart monit
  tags:
    - fail2ban
