- name: Remove old Docker packages
  package:
    name: "{{ debian.remove_packages }}"
    state: absent
  tags:
    - docker

- name: Add docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
  tags:
    - docker

- name: Install basic list of packages
  package:
    name: "{{ debian.dep_packages }}"
    state: present
    update_cache: yes
  tags:
    - docker

- name: Add repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
  tags:
    - docker

- name: Install Docker packages
  package:
    name: "{{ debian.add_packages }}"
    state: present
  tags:
    - docker

- name: Add user to docker group
  user:
    name: "{{ ansible_env.USER }}"
    groups:
      - docker
    append: yes
  tags:
    - docker
